"""
Plain-language explanation of a risk score, in English and Hindi.

This is templated, not generated by an LLM, for three reasons: it has to be
reproducible when a reviewer re-runs the same inputs, it must never invent a
number that is not in the feature vector, and it has to work offline. The
templates read the *actual* top contributions from the scorer, so the sentence and
the factor bars can never disagree.

Hindi is not a machine translation of the English string; both are written against
the same slot values, so each reads naturally in its own language.
"""

from __future__ import annotations

from typing import Sequence

from .config import ALERT_TIERS


def _mm(value: float | None) -> str:
    if value is None:
        return "—"
    return f"{value:.0f} mm" if value >= 10 else f"{value:.1f} mm"


def _cumecs(value: float | None) -> str:
    if value is None:
        return "—"
    if value >= 1000:
        return f"{value:,.0f} m³/s"
    return f"{value:.1f} m³/s"


def _ordinal_pct(p: float | None) -> str | None:
    if p is None:
        return None
    return f"{p:.0f}th percentile"


def _season_hi(month: int) -> str:
    if month in (6, 7, 8, 9):
        return "मानसून"
    if month in (10, 11, 12):
        return "उत्तर-पूर्वी मानसून / मानसून-उपरांत"
    return "मानसून-पूर्व"


def _season_en(month: int) -> str:
    if month in (6, 7, 8, 9):
        return "south-west monsoon"
    if month in (10, 11, 12):
        return "post-monsoon / north-east monsoon"
    return "pre-monsoon"


def factor_sentence(factor: dict, fv: dict) -> tuple[str, str]:
    """One clause explaining a single factor, with the real number in it."""
    rain, river, terrain, history = fv["rain"], fv["river"], fv["terrain"], fv["history"]
    key = factor["key"]

    if key == "rain_24h":
        cls = fv["imd_class"]
        return (
            f"{_mm(rain.get('rain_24h_mm'))} of rain has fallen in the last 24 hours "
            f"({cls['label_en'].lower()} by IMD's scale)",
            f"पिछले 24 घंटों में {_mm(rain.get('rain_24h_mm'))} वर्षा हुई है "
            f"(IMD श्रेणी: {cls['label_hi']})",
        )
    if key == "rain_72h":
        return (
            f"{_mm(rain.get('rain_72h_mm'))} has accumulated over three days, so the ground has had no time to drain",
            f"तीन दिनों में {_mm(rain.get('rain_72h_mm'))} वर्षा जमा हुई है, जिससे जल निकासी का समय नहीं मिला",
        )
    if key == "rain_forecast_24h":
        return (
            f"a further {_mm(rain.get('rain_next_24h_mm'))} is forecast in the next 24 hours",
            f"अगले 24 घंटों में {_mm(rain.get('rain_next_24h_mm'))} और वर्षा का पूर्वानुमान है",
        )
    if key == "rain_forecast_72h":
        return (
            f"{_mm(rain.get('rain_next_72h_mm'))} is forecast over the next three days",
            f"अगले तीन दिनों में {_mm(rain.get('rain_next_72h_mm'))} वर्षा का पूर्वानुमान है",
        )
    if key == "discharge_percentile":
        pct = _ordinal_pct(river.get("percentile_for_season"))
        years = river.get("climatology_years")
        return (
            f"the river is running at the {pct} for this time of year, "
            f"measured against the {years} GloFAS reanalysis"
            if pct
            else "the river is above its seasonal normal",
            f"नदी इस समय वर्ष के लिए {pct} पर बह रही है, जो {years} ग्लोफास पुनर्विश्लेषण पर आधारित है"
            if pct
            else "नदी अपने मौसमी सामान्य स्तर से ऊपर है",
        )
    if key == "discharge_ratio":
        ratio = river.get("ratio_to_seasonal_median")
        return (
            f"discharge is {_cumecs(river.get('current_cumecs'))}, "
            f"{ratio:.1f}× the seasonal median of {_cumecs(river.get('seasonal_median_cumecs'))}"
            if ratio
            else f"discharge is {_cumecs(river.get('current_cumecs'))}",
            f"प्रवाह {_cumecs(river.get('current_cumecs'))} है, जो मौसमी माध्यिका "
            f"{_cumecs(river.get('seasonal_median_cumecs'))} का {ratio:.1f} गुना है"
            if ratio
            else f"प्रवाह {_cumecs(river.get('current_cumecs'))} है",
        )
    if key == "discharge_trend":
        trend = river.get("trend_cumecs_per_day")
        if trend is not None and trend > 0:
            return (
                f"the river is still rising, at about {_cumecs(trend)} per day",
                f"नदी अभी भी बढ़ रही है, लगभग {_cumecs(trend)} प्रतिदिन",
            )
        return (
            "the river has begun to recede",
            "नदी का जलस्तर घटने लगा है",
        )
    if key == "soil_saturation":
        sm = rain.get("soil_moisture")
        return (
            f"the soil is already holding {sm:.2f} m³/m³ of water, so new rain will run off rather than soak in"
            if sm is not None
            else "the soil is already wet, so new rain will run off",
            f"मिट्टी में पहले से {sm:.2f} m³/m³ जल है, इसलिए नई वर्षा सोखी नहीं जाएगी बल्कि बहेगी"
            if sm is not None
            else "मिट्टी पहले से गीली है, इसलिए नई वर्षा बहकर जाएगी",
        )
    if key == "terrain_susceptibility":
        inputs = terrain.get("inputs", {})
        elev = inputs.get("elevation_m")
        dist = inputs.get("dist_to_water_km")
        bits_en, bits_hi = [], []
        if elev is not None:
            bits_en.append(f"the land sits at {elev:.0f} m")
            bits_hi.append(f"भूमि {elev:.0f} मीटर पर है")
        if dist is not None:
            bits_en.append(f"open water is {dist:.1f} km away")
            bits_hi.append(f"जलस्रोत {dist:.1f} किमी दूर है")
        if inputs.get("coastal"):
            bits_en.append("and tidal backwater can block drainage")
            bits_hi.append("और ज्वारीय पानी निकासी रोक सकता है")
        return (
            "the terrain itself is susceptible — " + ", ".join(bits_en) if bits_en else "the terrain is susceptible",
            "भूभाग स्वयं संवेदनशील है — " + ", ".join(bits_hi) if bits_hi else "भूभाग संवेदनशील है",
        )
    if key == "historical_frequency":
        recent = history.get("most_recent") or {}
        count = history.get("count", 0)
        if recent:
            return (
                f"this location has {count} recorded flood events since 2005, most recently in {recent.get('date','')[:4]}",
                f"इस स्थान पर 2005 से {count} दर्ज बाढ़ घटनाएँ हैं, सबसे हाल की {recent.get('date','')[:4]} में",
            )
        return ("this location has a history of flooding", "इस स्थान का बाढ़ का इतिहास रहा है")

    return (factor["label_en"], factor["label_hi"])


def build_explanation(
    loc: dict,
    fv: dict,
    scored: dict,
    factors: Sequence[dict],
    tier: dict,
    confidence: dict,
    trajectory: Sequence[dict],
    peak: dict | None,
) -> dict:
    """Assemble the narrative shown in the hyperlocal detail panel."""
    from datetime import datetime

    month = datetime.now().month
    top = [f for f in factors if f["is_top"]][:3]
    clauses = [factor_sentence(f, fv) for f in top]

    name_en = loc["name"]
    name_hi = loc.get("name_hi", loc["name"])
    score = scored["score"]

    lead_en = (
        f"{name_en} is at {score:.0f}/100 — {tier['label_en'].split('—')[0].strip().lower()} "
        f"on the IMD four-colour scale."
    )
    lead_hi = f"{name_hi} का जोखिम स्कोर {score:.0f}/100 है — IMD चार-रंग पैमाने पर {tier['label_hi'].split('—')[0].strip()}।"

    body_en = "Driving this: " + "; ".join(c[0] for c in clauses) + "."
    body_hi = "मुख्य कारण: " + "; ".join(c[1] for c in clauses) + "।"

    # Say which flood mechanism set the score when it outweighed the averaged evidence.
    dom = scored.get("dominant") or {}
    if dom and dom.get("score", 0) > scored.get("weighted_score", 0) and dom.get("score", 0) >= 25:
        if dom["mechanism"] == "riverine":
            body_en = "This is a river-flood signal. " + body_en
            body_hi = "यह नदी-बाढ़ का संकेत है। " + body_hi
        else:
            body_en = "This is an intense-rainfall (pluvial) flood signal. " + body_en
            body_hi = "यह तीव्र वर्षा से जलभराव/बाढ़ का संकेत है। " + body_hi

    tail_en, tail_hi = "", ""
    if peak and peak["hours"] > 0:
        tail_en = f" {peak['label_en']}, at about {peak['score']:.0f}/100."
        tail_hi = f" {peak['label_hi']}, लगभग {peak['score']:.0f}/100 पर।"
    elif peak:
        tail_en = " Conditions are at their peak now and the forecast eases from here."
        tail_hi = " स्थिति अभी शिखर पर है और आगे सुधार का पूर्वानुमान है।"

    # Lower-case only the leading character: blunt .lower() would turn "IQR" and
    # "GloFAS" into mush.
    reason_en = confidence["reasons_en"][0]
    reason_en = reason_en[0].lower() + reason_en[1:] if reason_en else ""
    conf_en = f" Confidence is {confidence['label_en'].split()[0].lower()}: {reason_en}."
    conf_hi = f" विश्वसनीयता {confidence['label_hi'].split()[0]}: {confidence['reasons_hi'][0]}।"

    return {
        "headline_en": lead_en,
        "headline_hi": lead_hi,
        "narrative_en": f"{lead_en} {body_en}{tail_en}{conf_en}",
        "narrative_hi": f"{lead_hi} {body_hi}{tail_hi}{conf_hi}",
        "bullets_en": [c[0][0].upper() + c[0][1:] for c in clauses],
        "bullets_hi": [c[1] for c in clauses],
        "season_en": _season_en(month),
        "season_hi": _season_hi(month),
        "method_note_en": (
            f"Score is a weighted blend of {len(scored['weights'])} named features "
            f"({int((1-scored['ml_blend_weight'])*100)}% rule-based"
            + (
                f", {int(scored['ml_blend_weight']*100)}% logistic model trained on past events)."
                if scored.get("ml_probability") is not None
                else ", no trained model loaded)."
            )
        ),
        "method_note_hi": (
            f"स्कोर {len(scored['weights'])} नामित कारकों का भारित मिश्रण है "
            f"({int((1-scored['ml_blend_weight'])*100)}% नियम-आधारित"
            + (
                f", {int(scored['ml_blend_weight']*100)}% प्रशिक्षित मॉडल)।"
                if scored.get("ml_probability") is not None
                else ", कोई प्रशिक्षित मॉडल लोड नहीं)।"
            )
        ),
    }


def response_actions(tier: dict) -> dict:
    """The NDMA-aligned action block that sits under the alert badge."""
    return {
        "tier": tier["key"],
        "imd_meaning_en": tier["imd_meaning_en"],
        "imd_meaning_hi": tier["imd_meaning_hi"],
        "ndma_action_en": tier["ndma_action_en"],
        "ndma_action_hi": tier["ndma_action_hi"],
    }


def national_summary_text(counts: dict[str, int], total: int, worst: Sequence[dict]) -> dict:
    """The one-line national situation report at the top of the country view."""
    red, orange = counts.get("red", 0), counts.get("orange", 0)
    # Name the places in the reader's own script; a Hindi sentence that lists
    # "Silchar, Dibrugarh, Surat" in Latin reads half-translated.
    names_en = ", ".join(w["location"]["name"] for w in worst[:3])
    names_hi = ", ".join(
        w["location"].get("name_hi") or w["location"]["name"] for w in worst[:3]
    )

    if red:
        en = (
            f"{red} location{'s' if red != 1 else ''} at Red and {orange} at Orange out of {total} monitored. "
            f"Highest risk: {names_en}."
        )
        hi = f"{total} निगरानी स्थानों में {red} लाल एवं {orange} नारंगी श्रेणी में। सर्वाधिक जोखिम: {names_hi}।"
    elif orange:
        en = f"No Red alerts. {orange} location{'s' if orange != 1 else ''} at Orange out of {total} monitored. Watch: {names_en}."
        hi = f"कोई लाल चेतावनी नहीं। {total} में से {orange} स्थान नारंगी श्रेणी में। निगरानी: {names_hi}।"
    else:
        en = f"No Red or Orange alerts across {total} monitored locations. Highest current risk: {names_en}."
        hi = f"{total} निगरानी स्थानों में कोई लाल या नारंगी चेतावनी नहीं। वर्तमान सर्वाधिक जोखिम: {names_hi}।"
    return {"en": en, "hi": hi}
